### ISSUE TITLE
Line 165 - ebyte.py -  raise UserWarning(f'not a valid property: {err}')

### ISSUE THREAD

**Issue by Dukat-Gul** [vindolin/python_ebyte_lora#1]
Not sure if this is me, I cloned your repository and before I make any adjustments (my pins are different [M0=22, M1=27 for the E22 based waveshare SX126x based LoRa hats.
SX1268_433M_LoRa_HAT `https://www.waveshare.com/wiki/SX1268_433M_LoRa_HAT`
E22-400T22S `http://www.ebyte.com/downpdf.aspx?id=458` 
and/or
SX1262_915M_LoRa_HAT `https://www.waveshare.com/wiki/SX1262_915M_LoRa_HAT` 
E22-900T22S `https://www.ebyte.com/en/downpdf.aspx?id=467`

I tried to run the command with anything (see paste below --help) and I get an error.

$ python ebyte.py --help
  File "ebyte.py", line 165
    raise UserWarning(f'not a valid property: {err}')
                                                   ^
SyntaxError: invalid syntax

wondered if it was a permissions thing.... seems no

$ sudo python ebyte.py --help
  File "ebyte.py", line 165
    raise UserWarning(f'not a valid property: {err}')
                                                   ^
SyntaxError: invalid syntax

**Comment by vindolin** [comment]
What Python version are you using?
Format strings `f'not a valid property: {err}'` were introduced in Python 3.

**Comment by Dukat-Gul** [comment]
Thanks, I didnt specify python3 (I used python, which is v2.7 on my system).
